### ISSUE TITLE
Issue with weak references

### ISSUE THREAD

**Issue by dumbo93** [oslofjord/sanity-linq#10]
Hey, 

In sanity I have created a document which consist of a list of references that are weak. I have noticed that in sanity-linq a sanity reference only consist of a reference, value, type and key. 
WhenI then use sanity-linq with my schemas the weak condition despair and are set to default strong. 

Would it be possible to add this feature?

Thanks for answers :)

**Comment by rvanoord** [comment]
Hi,

I have attempted to add support for weak references to the SanityReference type now. Added to version 1.3.7 of the Sanity LINQ Client.

**Comment by dumbo93** [comment]
Great! Thank you!

Would you like to make this version availabole as a NuGet package?

**Comment by rvanoord** [comment]
Hi! The package should be available now.

**Comment by dumbo93** [comment]
Thank you so much :)
