### ISSUE TITLE
Support for Contains

### ISSUE THREAD

**Issue by Andrioden** [oslofjord/sanity-linq#12]
Hello! Is it possible to add support for the `contains `where constraint?

``` c#
public async Task<List<T>> GetAll<T>(List<string> ids) where T : SanityDocument
{
    return await _context
        .DocumentSet<T>()
        .Where(p => ids.Contains(p.Id))
        .ToListAsync();
}
```

Throws exception

`Exception while executing function: System_SanityWebHook. Sanity.Linq: Method call Contains not supported.`

**Comment by rvanoord** [comment]
Support for "Contains" has now been added to version 1.4.2. This should support a number of scenarios including the following queries:

```csharp
// *[id in [ "id1", "id2", "id2"]]
var ids= new [] [ "id1", "id2", "id2"];
docs.Where(d =>ids.Contains(d.Id))

// *["id1" in ids]
docs.Where(d => d.Ids.Contains("id1"))

// *[lookup in ids]
docs.Where(d => d.Ids.Contains(d.Lookup))
```

**Comment by Andrioden** [comment]
Tested it, it works! Thanks for a very quick response!
