### ISSUE TITLE
What is the license for this library?

### ISSUE THREAD

**Issue by pmbanka** [oslofjord/sanity-linq#14]
The license on the repo level says MIT: https://github.com/oslofjord/sanity-linq/blob/master/LICENSE

But in src we have GPL: https://github.com/oslofjord/sanity-linq/blob/master/src/LICENCE

In the code, it also says GPL: https://github.com/oslofjord/sanity-linq/blob/master/src/Sanity.Linq/SanityDataContext.cs#L13

So which one is it?

**Comment by rvanoord** [comment]
Hi,
The project was originally GPL, but was quickly changed to MIT at the request of staff at Sanity. It looks like we forgot to update this in the code files.
The correct licence is MIT.
