### ISSUE TITLE
Does not support generic types

### ISSUE THREAD

**Issue by anarandjic** [oslofjord/sanity-linq#16]
If we have field that is referenced to different types of pages (article page, product page, landing page) I am not able to retreive reference by SanityReference type. Same is for blocks, if we have different types of blocks VideoBlock,TextBlock which are all derived from BaseBlock, I am no able to retreive different blocks under same type. My guess is that you should add typenamehandling serialization setting.

**Comment by rvanoord** [comment]
Hi,

If you use the JObject type you should be able to retrieve the data. Then
you can implement your own handler to convert to the respective types.

**Comment by anarandjic** [comment]
Thanks for advice, I will try but my guess is that this will solve issue.
