### ISSUE TITLE
Raw client giving errors

### ISSUE THREAD

**Issue by anna-Kop** [oslofjord/sanity-linq#19]
Hello!

I'm using the Sanity LINQ client in my .NET core project. 

I am able to use the "normal" queries just fine, e.g. `var posts = sanity.DocumentSet<Post>();`, but when I try to do a raw query with groq I get errors. I must be doing something wrong, but I cannot figure out what.

Here are my test queries:
```
var client = new Sanity.Linq.SanityClient(SanityOptions);
var resString = await client.FetchAsync<string>("*[_id == \"privacyStatement\"]");
var result = await client.FetchAsync<JObject>("*[_id == \"privacyStatement\"]");

```
Both tests give the following error:
"Failed to deserialize Sanity response: {\"ms\":8,\"query\":\"*[_id == \\\"privacyStatement\\\"]\",\"result\":[{\"_createdAt\":\"2020-0319T13:57:29Z\",\"_id\":\"privacyStatement\",\"_rev\":\"exe5DOSPM7n2I8TpbDSP5g\",\"_type\":\"privacyStatement\",\"_updatedAt\":\"2020-08-11T12:49:27Z\",\"body\":[{\"_key\":\"a0e6e98a28fb\",\"_type\":\"block\",\"children\":[{\"_key\":\"a0e6e98a28fb0\",\"_type\":\"span\",\"marks\":[],\"text\":\"Privacy Statement \"}],\"markDefs\":[],\"style\":\"h1\"},{\"_key\":\"5d0e643e7ae3\",\"_type\":\"block\",\"children\":[{\"_key\":\"5d0e643e7ae30\",\"_type\":\"span\",\"marks\":[],\"text\":\"This is a test\"}],\"markDefs\":[],\"style\":\"normal\"}]}]}"

So it finds the correct document, but it cannot return it...

The privacyStatement document type contains block content if that has anything to do with it.

Can you **please** help me figure out what is wrong?

**Comment by rvanoord** [comment]
Hi,

I assume the result is actually an array (containing one object), rather
than a simple object. Maybe it would work better if you used JArray instead
of JObject to deserialize.

**Comment by anna-Kop** [comment]
This solved it, thank you 👍
