### ISSUE TITLE
Where to intantiate a new SanityDataContext?

### ISSUE THREAD

**Issue by Warrenayiss** [oslofjord/sanity-linq#25]
It may be a dumb question but I'm trying to use Sanity Linq on my blazor project and don't know where to instantiate the DataContext

**Comment by rvanoord** [comment]
Hi! 
You can instantiate the context wherever you want. In a larger project it would make sense to register both the Sanity options and the SanityDataContext as services in Startup.
See https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0&pivots=webassembly

Obviously you should think twice about instantiating it with a private key on the client side.

**Comment by Warrenayiss** [comment]
All this is too confusing for me. There is no error when I put it in startup.cs but I wasn't able to use it in razor components or a class. It doesn't accept the "var..."

**Comment by rvanoord** [comment]
Would you be able to share some of your code?

**Comment by rvanoord** [comment]
Added worklog from 02.03.2021 10:00 to 02.03.2021 12:00 (2:00)

**Comment by Warrenayiss** [comment]
In the file startup.cs:
![image](https://user-images.githubusercontent.com/41448972/107144294-31d11780-6932-11eb-937a-1a5f11327b70.png)

In the Product.cs file:
![image](https://user-images.githubusercontent.com/41448972/107144316-5f1dc580-6932-11eb-8f4e-a53a4f2fcffb.png)


Is it possible to find an open source application of Sanity Linq in blazor web assembly?

**Comment by rvanoord** [comment]
Here's one way of adding the services to your container in startup.cs:
```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

// other code

public virtual void ConfigureServices(IServiceCollection services)
{
   services.AddOptions();

   // Read configuration from appsettings.json
   services.Configure<SanityOptions>(Configuration.GetSection("sanity"));
   
   // Add SanityOptions object to container
   services.AddTransient(s => s.GetService<IOptionsSnapshot<SanityOptions>>().Value);
   
  // Add SanityDataContext to container
   services.AddScoped<SanityDataContext>();


  // Add ProductRepository (see below)
  services.AddScoped<ProductRepository>()

  // Àdd other services....
  
}
   
```

Usually you should place your data model (Product) in a different class to the data repository methods (GetProductAsync).
Your repository class might look like this:

```csharp

public class ProductRepository
{
    // Constructor which takes SanityDataContext as a dependency (injected from container)
    public ProductRepository(SanityDataContext sanity)
    {
         this._sanity = sanity;
     }

     private readonly SanityDataContext _sanity;
     
     public async Task<Product> GetProductAsync(string id)
     {
          var products = _sanity.DocumentSet<Product>();
          var products = await products.Where(p => p.ProductId == id).FirstOrDefaultAsync();
          return product;
     }

}


```

Then you can use this repository by injecting it into your blazor component (.razor file):

```
@inject ProductRepository Products

```
