### ISSUE TITLE
enhancement: SanityFile

### ISSUE THREAD

**Issue by sven5** [oslofjord/sanity-linq#36]
Hi,

it seems that the file asset type is currently missing.
(https://www.sanity.io/docs/file-type)

the Json representation would be like the following:

```
 "file1": {
    "_type": "file",
    "asset": {
      "_ref": "file-05baff86caee1cda017d525ace439158effbecf2-pdf",
      "_type": "reference"
    }
  },
```

**Comment by piotr-szczygiel** [comment]
Do you have any solution/workaround to create the missing type on our own?

**Comment by sven5** [comment]
Solution is simple:
```
 public class SanityFile : SanityObject
    {
        public SanityFile() : base()
        {
            SanityType = "file";
        }

        public SanityReference<SanityFileAsset> Asset { get; set; }
    }
```

**Comment by rvanoord** [comment]
Thanks for your suggestions @sven5!

**Comment by sven5** [comment]
@rvanoord  Could you please release a new nuget package? Thanks!
