### ISSUE TITLE
Mutations generate invalid request body

### ISSUE THREAD

**Issue by roycornelissen** [oslofjord/sanity-linq#48]
Hi, I'm trying to use this client to construct a patch request where I remove an item from an array. This works when using the raw HTTP Mutations API, but I get an error when I try this using the C# client. This is the code:

```csharp
var mut = client.BeginTransaction<MyDoc>();
mut.PatchById(new Sanity.Linq.Mutations.SanityPatchById<MyDoc>("some-id")
{
    Unset = new[] { "accessControlList[_key==\"some-key-value\"]" }
});
var x = await client.CommitMutationsAsync<MyDoc>(mut);
```

The response is a `Bad Request` with the following message: `Unknown field "innerBuilder"`. When capturing the request with Fiddler, I see that it's sending the following request body:

![image](https://user-images.githubusercontent.com/641868/163388954-a0ccda6c-3ccf-405b-b811-4f0b392c21dd.png)

I'm using API version `v2021-10-21`

**Comment by roycornelissen** [comment]
Update: noticed that any patch request raises this problem. Fixed it by putting `JsonIgnore` on the `InnerBuilder` property so that it doesn't end up in the serialized request.

**Comment by rvanoord** [comment]
Sounds like a good fix. Can this issue be closed now?
