### ISSUE TITLE
StackOverflowException when using recursive model

### ISSUE THREAD

**Issue by chtombre** [oslofjord/sanity-linq#8]
I have a model structured like this:

`
public class NavigationItem : SanityDocument {
    public string Name { get; set; }
    public List<NavigationItem> Items { get; set; }
}
`

I guess because the model is self-referencing, the query is looped indefinitely and leeds to a stackoverflow. 

I'm not sure if I should go ahead and refactor my sanity-structure to go around this problem, or if you could introduce a way to tell how many levels deep the recursive query goes?

I'm using v1.3.3

**Comment by rvanoord** [comment]
This issue has been resolved in v1.3.6.

Nesting is now limited to 7 levels by default, but it is possible to override this setting at the document set level:
```
// Limit nesting to two levels
var blogPosts = sanity.DocumentSet<BlogPost>(maxNestingLevel: 2).ToListAsync();
```
