### ISSUE TITLE
Sanity reference include issues

### ISSUE THREAD

**Issue by passeride** [oslofjord/sanity-linq#9]
Hello fine people

I'm having some issues where in an array the include attribute (also if i .Include<> on set).
Removes the "sanity_key" on the reference object. 
So when the object is updated/saved to sanity, it will complain of missing keys. 
However if i do not include, then the key is present and no error is given. 

Schema I'm having trouble with: 
`    {
      name: "groups",
      title: "Groups",
      type: "array",
      of: [
        {
          type: "reference",
          to: [{ type: "group" }]
        }
      ],
      validation: Rule => Rule.unique()
    },
`

Thanks for answers :)

**Comment by passeride** [comment]
I see now that sanity either returns a "Reference" that has a key or the object referenced and then it does not have a key. it's possible to get both using GROQ, but then you have some serializing issues. 

This query will return a group object that has the reference key, and a groupsObj that is the referenced object. But it does complicate things. 
`
*[_type == "person"]{..., 'groupsObj': groups[]->{...}}
`

I guess it's not an issue with you guys:) sorry to bother you

**Comment by rvanoord** [comment]
Hi @passeride,

Thanks for sharing your issue and the solution in GROQ. 

The [Include()] attribute takes an optional argument for specifying the source field name. This effectively allows you to retrieve the same field twice, but with different names in the resulting model. In your case you could use this to retreive one "included" version of the array, and one list of references.

Example:
```
// References
public JObject[] Groups { get, set; }

// Objects
[Include("groups")]
public Group[] GroupObjects { get, set; }

```

Another way of including both is by using the inbuilt SanityReference class in combination with your object class:

```
[Include]
public List<SanityReference<Group>> Groups { get; set; }

```
This basically gives you a list of SanityReference objects with a nested Group object, which in practice should give a similar result to your GROQ solution.

**Comment by passeride** [comment]
Hey

Thanks for quick answer.

I also see now that if `SanityReference.Value` was not unmapped from a JSON standpoint, this groq query could result in the best of booth worlds

`*[_type == "person"]{...,'groups':groups[]{..., 'Value':^->}}`

Allowing you to (When Include attribute is used) to keep the `ID` while also getting the referenced object. 

Resulting JSON
`

groups |  
-- | --
0 |  
Value |  
Value._createdAt | "2019-09-09T09:51:40Z"
Value._id | "xxxxxxxxxxxxxxxxxxxxxxxxx"
Value._rev | "xxxxxxxxxxxxxxxxxxxxxxxxx"
Value._type | "group"
Value._updatedAt | "2019-09-09T09:51:40Z"
Value.name | "Talenter"
_key | "xxxxxxxxxxxxxxxxxxxxxxxxx"
_ref | "xxxxxxxxxxxxxxxxxxxxxxxxx"
_type | "reference"
1 |  
Value |  
Value._createdAt | "2019-09-09T10:11:36Z"
Value._id | "xxxxxxxxxxxxxxxxxxxxxxxxx"
Value._rev | "xxxxxxxxxxxxxxxxxxxxxxxxx"
Value._type | "group"
Value._updatedAt | "2019-09-17T08:16:55Z"
Value.name | "Hunks"
_key | "xxxxxxxxxxxxxxxxxxxxxxxxx"
_ref | "xxxxxxxxxxxxxxxxxxxxxxxxx"
_type | "reference"
`

There might be a good reason this would not work, but i thought you might wanna know:) 

Thanks for a good product and quick answer. 

Best Regards / MvH 
Passeride
